### ISSUE TITLE
Fedora WSL

### ISSUE THREAD

**Issue by king-11** [king-11/dotrc#3]
WSL Installation
```powershell
docker run --name fedora39 fedora:39
docker export -o fedora-39-rootfs.tar fedora39
```

User Setup
```powershell
mkdir $HOME\wsl\fedora
wsl --import fedora $HOME\wsl\fedora $HOME\Downloads\fedora-39-rootfs.tar
wsl -d fedora
```

Packages
```
sudo dnf install util-linux-user git
sudo dnf groupinstall "Development Tools" "Development Libraries"
sudo dnf -y install make automake gcc gcc-c++ kernel-devel
sudo dnf -y install zlib-devel libffi-devel openssl-devel bzip2-devel readline-devel sqlite-devel xz-devel
sudo dnf clean all
```

Export
```
wsl --export fedora $HOME\Downloads\fedora-wsl.tar
```

**Comment by king-11** [comment]
Libcuda Fix

https://github.com/microsoft/WSL/issues/5548#issuecomment-990521993

**Comment by king-11** [comment]
Install pyenv using brew only
brew install python-tk

**Comment by king-11** [comment]
```
sudo -e /etc/wsl.conf
[boot]
systemd=true
```

**Comment by king-11** [comment]
`pkg-config` brew install conflicts with system one

```
brew update\
brew upgrade\
brew remove --ignore-dependencies pkg-config\
brew install -vds --env=super pkg-config
```

**Comment by king-11** [comment]
GPG signing fix

```
GPG_TTY=$(tty)
export GPG_TTY
```

**Comment by king-11** [comment]
Closing since most of the setup is done with final comment will keep posting in case of new additions. Commit reference 

king-11/dotrc@ca012ed0392406565cf64d9eec541f9b7834e8c8

**Comment by king-11** [comment]
- dotnet install https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install
- dotnet tab completions https://learn.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete
- nuget https://learn.microsoft.com/en-us/nuget/install-nuget-client-tools

**Comment by king-11** [comment]
en_US.UTF-8

```
sudo echo "LANG=en_US.UTF-8" > /etc/local.conf
sudo dnf install langpacks-en
localectl set-locale LANG=en_US.UTF-8
```

**Comment by king-11** [comment]
[wslview](https://wslutiliti.es/wslu/install.html#ubuntu) for access browser through wsl.

```
export DISPLAY=:0 # not required as GUI supported
export BROWSER=/usr/bin/wslview
```

wayland server not found fix https://github.com/microsoft/WSL/issues/11261#issuecomment-2011901398

**Comment by king-11** [comment]
setting up localhost port transfer: https://abdus.dev/posts/fixing-wsl2-localhost-access-issue/

**Comment by king-11** [comment]
Intellij slow in WSL: https://github.com/microsoft/WSL/issues/8995#issuecomment-1380187901

**Comment by king-11** [comment]
WSL slow: https://github.com/microsoft/WSL/issues/873

**Comment by king-11** [comment]
clock issue: https://github.com/microsoft/WSL/issues/10006

WSL version: 2.1.1
```powershell
wsl --update --pre-release
```

Update: breaks fedora instead use this: https://github.com/microsoft/WSL/issues/8204#issuecomment-1339506778

**Comment by king-11** [comment]
```
sudo dnf upgrade --refresh
sudo dnf install dnf-plugin-system-upgrade
sudo dnf system-upgrade download --releaserver=40
export DNF_SYSTEM_UPGRADE_NO_REBOOT=1
sudo -E dnf system-upgrade reboot
sudo -E dnf system-upgrade upgrade
sudo dnf upgrade --refresh
```

**Comment by king-11** [comment]
to attach yubikey to wsl

```powershell
usbipd bind --busid 2-4
usbipd attach --wsl --busid 2-4
```

after this we sometimes have to reset gpg agent for ssh to work
```bash
gpg --card-status
gpg-connect-agent updatestartuptty /bye
```

**Comment by king-11** [comment]
for using ghostty from launcher with zsh as default shell we need to make export for PATH otherwise it won't show up as mentioned in this [issue](https://github.com/ghostty-org/ghostty/issues/3333)

>I was facing the same issue on Fedora 41 (KDE), when my shell was set to zsh. I was able to fix it by creating ~/.zprofile and adding this line to it:
>```
>PATH=$HOME/.local/bin:$HOME/bin:$PATH
>```
>It was already in ~/.zshrc but it wasnt enough

**Comment by lakshya-singh-glean** [comment]
https://github.com/zellij-org/zellij/pull/3047#issuecomment-2530939018
